// <auto-generated> by tools/build_sprites.py – do not edit by hand </auto-generated>
namespace RandoApp;

public static partial class Sprites
{
    static readonly Dictionary<string, Anim> All = new()
    {
        ["0282/idle"] = new("0282-idle.png", [6, 12, 6, 12]),
        ["0025/idle"] = new("0025-idle.png", [40, 2, 3, 3, 3, 2]),
        ["0094/idle"] = new("0094-idle.png", [40, 4, 3, 3, 3, 3, 3, 4]),
        ["0004/idle"] = new("0004-idle.png", [12, 8, 8, 8]),
        ["0133/idle"] = new("0133-idle.png", [16, 16]),
        ["0448/idle"] = new("0448-idle.png", [40, 2, 2, 4, 2, 2]),
        ["0150/idle"] = new("0150-idle.png", [40, 2, 4, 6, 8, 6, 4, 2]),
        ["0143/sleep"] = new("0143-sleep.png", [30, 35]),
        ["0197/portrait"] = new("0197-portrait.png", [1]),
        ["0006/portrait"] = new("0006-portrait.png", [1]),
        ["0384/portrait"] = new("0384-portrait.png", [1]),
        ["0001/idle"] = new("0001-idle.png", [40, 6, 6]),
        ["0007/idle"] = new("0007-idle.png", [30, 2, 2, 4, 4, 4, 2, 2]),
        ["0134/idle"] = new("0134-idle.png", [60, 16]),
        ["0135/idle"] = new("0135-idle.png", [60, 16]),
        ["0136/idle"] = new("0136-idle.png", [12, 16, 12, 16]),
        ["0487/idle"] = new("0487-idle.png", [60, 40]),
        ["0483/idle"] = new("0483-idle.png", [80, 45]),
        ["0484/idle"] = new("0484-idle.png", [40, 30]),
        ["0250/idle"] = new("0250-idle.png", [12, 10, 12, 10, 12]),
        ["0249/idle"] = new("0249-idle.png", [30, 30]),
        ["0245/idle"] = new("0245-idle.png", [60, 10, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 10]),
        ["0643/idle"] = new("0643-idle.png", [90, 4, 8, 4, 8, 4]),
        ["0644/idle"] = new("0644-idle.png", [60, 10, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 10]),
        ["0646/idle"] = new("0646-idle.png", [40, 30]),
        ["0006/idle"] = new("0006-idle.png", [15, 15, 15, 15]),
        ["0009/idle"] = new("0009-idle.png", [32, 12, 4, 4, 4, 4, 4, 8]),
        ["0003/idle"] = new("0003-idle.png", [30, 16, 12, 16]),
        ["0383/idle"] = new("0383-idle.png", [60, 10, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 10]),
        ["0382/idle"] = new("0382-idle.png", [10, 14, 14, 14, 14, 10, 14, 14, 14, 14]),
        ["0384/idle"] = new("0384-idle.png", [14, 10, 14, 10]),
    };
}
