"""
Every Pokémon up to Gen 7 (#1–809) for PokéHub's team rows: the idle animation from PMD Sprite Collab
(https://sprites.pmdcollab.org/, facing the player) as a small strip in Assets/Species, plus the German and English names
from PokeAPI (https://github.com/PokeAPI/pokeapi, data/v2/csv). Writes SpeciesData.g.cs.

Run:  python tools/build_species.py
"""
import csv, io, os, sys, urllib.error, urllib.request, xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor
from PIL import Image

SPRITES = "https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/sprite"
PORTRAITS = "https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait"
NAMES = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_species_names.csv"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Assets", "Species")
MAX = 809
GERMAN, ENGLISH = "6", "9"


def get(url, tries=3):
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                return r.read()
        except urllib.error.HTTPError:
            raise  # 404 etc.: retrying won't help
        except Exception:
            if attempt == tries - 1:
                raise


def portrait(dex):
    """Fallback for species without a body sprite: their Mystery Dungeon portrait as a still frame."""
    try:
        img = Image.open(io.BytesIO(get(f"{PORTRAITS}/{dex:04d}/Normal.png"))).convert("RGBA")
    except Exception as e:
        return dex, None, str(e)
    img.save(os.path.join(OUT, f"{dex:04d}.png"), optimize=True)
    return dex, [1], None


def build(dex):
    """Idle strip of one species (portrait if Sprite Collab has no body sprite), or None."""
    folder = f"{SPRITES}/{dex:04d}"
    try:
        root = ET.fromstring(get(f"{folder}/AnimData.xml"))
        anims = {a.findtext("Name"): a for a in root.iter("Anim")}
        name = "Idle" if "Idle" in anims else "Walk"
        node = anims[name]
        while node.find("CopyOf") is not None:  # some animations just reference another one
            name = node.findtext("CopyOf")
            node = anims[name]
        fw, fh = int(node.findtext("FrameWidth")), int(node.findtext("FrameHeight"))
        durations = [int(d.text) for d in node.find("Durations")]
        sheet = Image.open(io.BytesIO(get(f"{folder}/{name}-Anim.png"))).convert("RGBA")
    except urllib.error.HTTPError:  # no body sprite yet for this species
        return portrait(dex)
    except Exception as e:
        return dex, None, str(e)
    frames = [sheet.crop((i * fw, 0, (i + 1) * fw, fh)) for i in range(len(durations))]  # row 0 = facing down
    boxes = [f.getbbox() for f in frames if f.getbbox()]
    if not boxes:
        return dex, None, "leer"
    l, t = min(b[0] for b in boxes), min(b[1] for b in boxes)
    r, b = max(b[2] for b in boxes), max(b[3] for b in boxes)
    frames = [f.crop((l, t, r, b)) for f in frames]
    w, h = frames[0].size
    strip = Image.new("RGBA", (w * len(frames), h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        strip.paste(f, (i * w, 0))
    strip.save(os.path.join(OUT, f"{dex:04d}.png"), optimize=True)
    return dex, durations, None


os.makedirs(OUT, exist_ok=True)
with ThreadPoolExecutor(12) as pool:
    results = sorted(pool.map(build, range(1, MAX + 1)))
missing = [(d, err) for d, durations, err in results if durations is None]
print(f"{MAX - len(missing)} Sprites, {len(missing)} ohne Sprite: {missing[:10]}")

names, english = {}, {}
for row in csv.DictReader(io.StringIO(get(NAMES).decode("utf-8"))):
    if int(row["pokemon_species_id"]) <= MAX and row["local_language_id"] in (GERMAN, ENGLISH):
        (names if row["local_language_id"] == GERMAN else english)[int(row["pokemon_species_id"])] = row["name"]
print(f"{len(names)} deutsche, {len(english)} englische Namen")

lines = ["// <auto-generated> by tools/build_species.py – do not edit by hand </auto-generated>",
         "// Sprites: PMD Sprite Collab (non-commercial fan use). Names: PokeAPI.",
         "namespace PokeHub;", "", "public static partial class Species", "{",
         "    /// <summary>Idle animation frame durations (1/60 s) per species that has a sprite.</summary>",
         "    static readonly Dictionary<int, int[]> Durations = new()", "    {"]
for dex, durations, _ in results:
    if durations:
        lines.append(f"        [{dex}] = [{', '.join(map(str, durations))}],")
lines += ["    };", "", "    static readonly string[] GermanNames =", "    ["]
for dex in range(1, MAX + 1):
    lines.append(f'        "{names.get(dex, "#" + str(dex))}",')
lines += ["    ];", "", "    static readonly string[] EnglishNames =", "    ["]
for dex in range(1, MAX + 1):
    lines.append(f'        "{english.get(dex, "#" + str(dex))}",')
lines += ["    ];", "}", ""]
open(os.path.join(ROOT, "SpeciesData.g.cs"), "w", encoding="utf-8").write("\n".join(lines))
print("SpeciesData.g.cs geschrieben")
