"""
Downloads theme sprites from PMD Sprite Collab (https://sprites.pmdcollab.org/) and cuts them into
small strips for the app (Assets/Sprites). Also writes SpriteData.g.cs with the frame timings.

Run:  python tools/build_sprites.py
Add a Pokémon: add a line to WANTED ("<dex no>", "<animation or 'portrait'>").
"""
import io, os, sys, urllib.request, xml.etree.ElementTree as ET
from PIL import Image

BASE = "https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Assets", "Sprites")

WANTED = [
    ("0282", "Idle"), ("0025", "Idle"), ("0094", "Idle"), ("0004", "Idle"),   # Guardevoir, Pikachu, Gengar, Glumanda
    ("0133", "Idle"), ("0448", "Idle"), ("0150", "Idle"),                     # Evoli, Lucario, Mewtu
    ("0143", "Sleep"),                                                        # Relaxo (schlafend)
    ("0197", "portrait"), ("0006", "portrait"), ("0384", "portrait"),         # Nachtara, Glurak, Rayquaza
    ("0001", "Idle"), ("0007", "Idle"),                                       # Bisasam, Schiggy (+ Glumanda) = Kanto-Starter
    ("0134", "Idle"), ("0135", "Idle"), ("0136", "Idle"),                     # Aquana, Blitza, Flamara (+ Evoli)
    # box Pokémon of the games (PokéHub "Spiel auswählen" / "Weiterspielen")
    ("0487", "Idle"), ("0483", "Idle"), ("0484", "Idle"),                     # Giratina (Platin), Dialga (Diamant), Palkia (Perl)
    ("0250", "Idle"), ("0249", "Idle"), ("0245", "Idle"),                     # Ho-Oh (HeartGold/Gold), Lugia (SoulSilver/Silber), Suicune (Kristall)
    ("0643", "Idle"), ("0644", "Idle"), ("0646", "Idle"),                     # Reshiram (Schwarz), Zekrom (Weiß), Kyurem (S2/W2)
    ("0006", "Idle"), ("0009", "Idle"), ("0003", "Idle"),                     # Glurak (Rot/Feuerrot), Turtok (Blau), Bisaflor (Blattgrün)
    ("0383", "Idle"), ("0382", "Idle"), ("0384", "Idle"),                     # Groudon (Rubin), Kyogre (Saphir), Rayquaza (Smaragd)
]

def get(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read()

def build_anim(dex, anim):
    root = ET.fromstring(get(f"{BASE}/sprite/{dex}/AnimData.xml"))
    node = next(a for a in root.iter("Anim") if a.findtext("Name") == anim)
    if node.find("CopyOf") is not None:  # some animations just reference another one
        return build_anim(dex, node.findtext("CopyOf"))
    fw, fh = int(node.findtext("FrameWidth")), int(node.findtext("FrameHeight"))
    durations = [int(d.text) for d in node.find("Durations")]
    sheet = Image.open(io.BytesIO(get(f"{BASE}/sprite/{dex}/{anim}-Anim.png"))).convert("RGBA")
    # row 0 = facing down (towards the player)
    frames = [sheet.crop((i * fw, 0, (i + 1) * fw, fh)) for i in range(len(durations))]
    boxes = [f.getbbox() for f in frames if f.getbbox()]
    l, t = min(b[0] for b in boxes), min(b[1] for b in boxes)
    r, b = max(b[2] for b in boxes), max(b[3] for b in boxes)
    frames = [f.crop((l, t, r, b)) for f in frames]
    w, h = frames[0].size
    strip = Image.new("RGBA", (w * len(frames), h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        strip.paste(f, (i * w, 0))
    name = f"{dex}-{anim.lower()}.png"
    strip.save(os.path.join(OUT, name))
    return name, durations

def build_portrait(dex):
    img = Image.open(io.BytesIO(get(f"{BASE}/portrait/{dex}/Normal.png"))).convert("RGBA")
    name = f"{dex}-portrait.png"
    img.save(os.path.join(OUT, name))
    return name, [1]

os.makedirs(OUT, exist_ok=True)
entries = []
for dex, kind in WANTED:
    try:
        name, durations = build_portrait(dex) if kind == "portrait" else build_anim(dex, kind)
        entries.append((f"{dex}/{kind.lower()}", name, durations))
        print(f"ok   {dex} {kind:8} -> {name} ({len(durations)} Bilder)")
    except Exception as e:
        print(f"FAIL {dex} {kind}: {e}", file=sys.stderr)

lines = ["// <auto-generated> by tools/build_sprites.py – do not edit by hand </auto-generated>",
         "namespace RandoApp;", "", "public static partial class Sprites", "{",
         "    static readonly Dictionary<string, Anim> All = new()", "    {"]
for key, name, durations in entries:
    lines.append(f'        ["{key}"] = new("{name}", [{", ".join(map(str, durations))}]),')
lines += ["    };", "}", ""]
open(os.path.join(ROOT, "Shared", "SpriteData.g.cs"), "w", encoding="utf-8").write("\n".join(lines))
print("SpriteData.g.cs geschrieben:", len(entries), "Einträge")
